// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {connection} from '../models';
import {query} from '../models';
import {db} from '../models';
import {influx} from '../models';

export function AddConnection(arg1:connection.ConnectionUpsert):Promise<void>;

export function CancelQuery(arg1:string):Promise<void>;

export function ClearQueryHistory():Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteSavedQuery(arg1:string):Promise<void>;

export function ExecuteQuery(arg1:query.QueryRequest):Promise<query.QueryResult>;

export function ExportQueryCSV(arg1:string):Promise<string>;

export function ExportQueryJSON(arg1:string):Promise<string>;

export function GetQuery(arg1:string):Promise<query.QueryJob>;

export function GetQueryHistory():Promise<Array<query.QueryHistoryItem>>;

export function ListConnections():Promise<Array<connection.ConnectionProfile>>;

export function ListDatabases(arg1:string):Promise<Array<db.DatabaseInfo>>;

export function ListDatabasesForProfile(arg1:connection.ConnectionUpsert):Promise<Array<db.DatabaseInfo>>;

export function ListFields(arg1:string,arg2:db.QueryScope,arg3:string):Promise<Array<influx.FieldInfo>>;

export function ListMeasurements(arg1:string,arg2:db.QueryScope):Promise<Array<influx.MeasurementInfo>>;

export function ListSavedQueries():Promise<Array<query.SavedQuery>>;

export function ListTags(arg1:string,arg2:db.QueryScope,arg3:string):Promise<Array<influx.TagInfo>>;

export function SaveQuery(arg1:query.SavedQuery):Promise<void>;

export function StartQuery(arg1:query.QueryRequest):Promise<string>;

export function TestConnection(arg1:string):Promise<void>;

export function TestConnectionProfile(arg1:connection.ConnectionUpsert):Promise<void>;
