// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1) {
  return window['go']['main']['DesktopApp']['AddConnection'](arg1);
}

export function CancelQuery(arg1) {
  return window['go']['main']['DesktopApp']['CancelQuery'](arg1);
}

export function ClearQueryHistory() {
  return window['go']['main']['DesktopApp']['ClearQueryHistory']();
}

export function DeleteConnection(arg1) {
  return window['go']['main']['DesktopApp']['DeleteConnection'](arg1);
}

export function DeleteSavedQuery(arg1) {
  return window['go']['main']['DesktopApp']['DeleteSavedQuery'](arg1);
}

export function ExecuteQuery(arg1) {
  return window['go']['main']['DesktopApp']['ExecuteQuery'](arg1);
}

export function ExportQueryCSV(arg1) {
  return window['go']['main']['DesktopApp']['ExportQueryCSV'](arg1);
}

export function ExportQueryJSON(arg1) {
  return window['go']['main']['DesktopApp']['ExportQueryJSON'](arg1);
}

export function GetQuery(arg1) {
  return window['go']['main']['DesktopApp']['GetQuery'](arg1);
}

export function GetQueryHistory() {
  return window['go']['main']['DesktopApp']['GetQueryHistory']();
}

export function ListConnections() {
  return window['go']['main']['DesktopApp']['ListConnections']();
}

export function ListDatabases(arg1) {
  return window['go']['main']['DesktopApp']['ListDatabases'](arg1);
}

export function ListDatabasesForProfile(arg1) {
  return window['go']['main']['DesktopApp']['ListDatabasesForProfile'](arg1);
}

export function ListFields(arg1, arg2, arg3) {
  return window['go']['main']['DesktopApp']['ListFields'](arg1, arg2, arg3);
}

export function ListMeasurements(arg1, arg2) {
  return window['go']['main']['DesktopApp']['ListMeasurements'](arg1, arg2);
}

export function ListSavedQueries() {
  return window['go']['main']['DesktopApp']['ListSavedQueries']();
}

export function ListTags(arg1, arg2, arg3) {
  return window['go']['main']['DesktopApp']['ListTags'](arg1, arg2, arg3);
}

export function SaveQuery(arg1) {
  return window['go']['main']['DesktopApp']['SaveQuery'](arg1);
}

export function StartQuery(arg1) {
  return window['go']['main']['DesktopApp']['StartQuery'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['DesktopApp']['TestConnection'](arg1);
}

export function TestConnectionProfile(arg1) {
  return window['go']['main']['DesktopApp']['TestConnectionProfile'](arg1);
}
